#:schema https://raw.githubusercontent.com/crate-ci/committed/refs/heads/master/config.schema.json

style = "conventional"

line_length = 80
merge_commit = false
no_fixup = false
subject_capitalized = false

allowed_types = [
  "chore",
  "docs",
  "feat",
  "fix",
  "perf",
  "refactor",
  "revert",
  "style",
  "test",
]

ignore_author_re = "(?i)^.*\\[bot\\] <.*>$"
